//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryDemo.remoteSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="remoteSoap.RemoteLibrarySoap")]
    public interface RemoteLibrarySoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddThis", ReplyAction="*")]
        int AddThis(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddThis", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddThisAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RemoteLibrarySoapChannel : LibraryDemo.remoteSoap.RemoteLibrarySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteLibrarySoapClient : System.ServiceModel.ClientBase<LibraryDemo.remoteSoap.RemoteLibrarySoap>, LibraryDemo.remoteSoap.RemoteLibrarySoap {
        
        public RemoteLibrarySoapClient() {
        }
        
        public RemoteLibrarySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteLibrarySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteLibrarySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteLibrarySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddThis(int a, int b) {
            return base.Channel.AddThis(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddThisAsync(int a, int b) {
            return base.Channel.AddThisAsync(a, b);
        }
    }
}
